import { ReleaseOverview } from "./release-overview-interface";

export const releaseOverviews: ReleaseOverview[] = [
    {
        quarter: 'Q1',
        year: 2018,
        summaryPoints: [],
        quarterOverviewPoints: [
            'Total global sales decreased 5.5% to $1.93 billion (decreased 7.5% in constant currency), resulting in a consolidated comparable store sales decrease of 5.3% (2.6% decrease in the U.S. and 11.6% decrease internationally). Consistent with the company’s expectations, new hardware sales decreased 7.9% while new software sales decreased 10.3%, with each of these categories impacted by the highly successful launch of the Nintendo Switch in the first quarter of fiscal 2017.  Software sales were further impacted by the strength of titles across platforms that launched in the prior fiscal year.  Pre-owned sales declined 5.8% and worldwide omnichannel sales decreased 46.0% due to limited allocation of the Nintendo Switch at launch, which drove a 92.9% increase in omnichannel sales in the first quarter of fiscal 2017.',
            'Digital sales and non-GAAP digital receipts increased 29.6% and 24.2%, respectively, excluding the first quarter 2017 revenues from Kongregate which was sold in July 2017.  On a reported basis, digital sales decreased 2.5% to $43.0 million, while non-GAAP digital receipts increased 16.2% to $273.7 million.',
            'Collectibles sales increased 24.4% to $142.4 million, driven by continued expansion of licensed merchandise offerings and unique product offerings.',
            'Technology Brands sales decreased 16.1% to $169.0 million, primarily due to less promotional activity and the overlap of the previously disclosed change in AT&T’s dealer compensation structure from the previous year.  Technology Brands GAAP operating earnings were $9.8 million.  Technology Brands operating earnings, excluding store closure and other charges, were $11.2 million compared to $18.4 million in the prior-year quarter.',
            'GameStop’s first quarter GAAP net income was $28.2 million, or $0.28 per diluted share, compared to net income of $59.0 million, or $0.58 per diluted share in the prior-year quarter. The first quarter results include store closure charges and other charges related to previously disclosed management changes of $12.6 million ($10.8 million net of taxes, or $0.11 per diluted share). ',
            'Excluding store closure and other charges, GameStop’s adjusted net income for the first quarter was $39.0 million, compared to adjusted net income of $63.6 million in the prior-year quarter.  Adjusted earnings per diluted share were $0.38 compared to adjusted earnings per diluted share of $0.63 in the prior-year quarter. ',
        ],
    },
    {
        quarter: 'Q2',
        year: 2018,
        summaryPoints: [],
        quarterOverviewPoints: [
            'Dan DeMatteo, executive chairman of GameStop’s board of directors, stated, “As our teams prepare for a busy and exciting holiday period, our board of directors, with the support of our financial and legal advisors, continues to conduct a comprehensive review of strategic and financial alternatives, including, but not limited to, a potential sale of the company.”',
            'Consistent with the company’s expectations, total global sales decreased 2.4% to $1.65 billion (decreased 2.9% in constant currency), resulting in a consolidated comparable store sales decrease of 0.5% (2.4% increase in the U.S. and 6.4% decrease internationally). New hardware sales increased 20.1%, driven by the launch of the Xbox One X and continued strong sales of the Nintendo Switch and PS4.  New software sales decreased 18.5% primarily due to the lack of significant title launches during the quarter.  Pre-owned sales declined 9.9%.',
            'Digital receipts increased 15.3% to $255.9 million, excluding the second quarter 2017 revenues from Kongregate, which was sold in July 2017.  On a reported basis, digital sales decreased 13.5% to $40.2 million due to the sale of Kongregate.',
            'Collectibles sales increased 15.7% to $141.7 million, driven by continued expansion of licensed merchandise offerings, new and improved product offerings and notable growth in apparel.',
            'Technology Brands operating earnings, increased 35.3% to $20.3 million compared to $15.0 million in the prior-year quarter, despite a 10.3% decline in sales to $168.9 million, primarily due to store closures relative to fiscal 2017.',
            'GameStop’s second quarter GAAP net income (loss) was ($24.9) million, or ($0.24) per diluted share, compared to net income of $22.2 million, or $0.22 per diluted share in the prior-year quarter.  Second quarter fiscal 2018 results include a non-operating tax charge of $29.6 million, or $0.29 per diluted share, related to the company’s previously disclosed tax matter in France.  The second quarter of fiscal 2017 included a benefit from business divestitures of $7.3 million (both before and after tax), or $0.07 per diluted share.',
            'Excluding the non-operating tax charge, GameStop’s adjusted net income for the second quarter was $4.7 million, compared to adjusted net income of $14.9 million in the prior-year quarter.  Adjusted earnings per diluted share were $0.05 compared to adjusted earnings per diluted share of $0.15 in the prior-year quarter.',
        ],
    },
    {
        quarter: 'Q3',
        year: 2018,
        summaryPoints: [],
        quarterOverviewPoints: [
            'Rob Lloyd, chief operating officer and chief financial officer, said, “We experienced solid growth in the third quarter, including double-digit growth across software, hardware, accessories and collectibles, underscoring GameStop’s leadership position in video games and our unique ability to satisfy all of our customers’ entertainment needs.  Notably, software sales benefited from a compelling title line-up compared to last year, including strength from Red Dead Redemption 2 and Spider-Man, as well as the earlier launch of Call of Duty compared to last year.  We are especially pleased with our performance in October, a month where The NPD Group disclosed that the U.S. physical video game industry grew by 46% while our U.S. physical video game revenue outpaced the industry and increased 63% resulting in market share gains.”',
            'Total global sales increased 4.8% (increased 6.3% in constant currency) to $2.1 billion, resulting in a consolidated comparable store sales increase of 2.1% (3.4% increase in the U.S. and 0.5% decrease internationally). New hardware sales increased 12.8%, driven by demand for Xbox One X and Sony PS4.  New software sales increased 10.9% driven by the strong slate of titles that launched during the quarter.  Accessories sales increased 32.6% on the strength of headset and controller sales.  Pre-owned sales declined 13.4%.',
            'Digital receipts increased 29.5% to $341.6 million driven primarily by strength in sales of digital currency.',
            'Collectibles sales increased 11.7% to $154.6 million due to continued growth in both our domestic and international collectibles business. ',
            'Technology Brands operating earnings increased 29.4% to $23.3 million compared to $18.0 million in the prior-year quarter, despite an 11.9% decline in sales to $171.1 million, primarily due to store closures relative to fiscal 2017.  ',
            'GameStop’s third quarter GAAP net income (loss) was ($488.6) million, or ($4.78) per diluted share, compared to net income of $59.4 million, or $0.59 per diluted share in the prior-year quarter.  Third quarter fiscal 2018 results include a non-operating, non-cash intangible asset impairment charge of $587.5 million, primarily related to goodwill and triggered by the sustained decline in the company’s share price. ',
        ],
    },
    {
        quarter: 'Q4',
        year: 2018,
        summaryPoints: [
            'Dan DeMatteo, GameStop’s executive chairman said, “This past year was a pivotal one for GameStop, capped by retail industry veteran George Sherman’s appointment as chief executive officer.  In conjunction with the board’s comprehensive review of strategic and financial alternatives, we executed the sale of Spring Mobile at an attractive valuation.  As a result, we are better positioned to drive shareholder value with an intense focus on leveraging our global gaming and collectibles business.  Additionally, we are significantly reducing leverage through the announced retirement of $350 million of outstanding notes, and we have increased flexibility with respect to future capital allocation opportunities.  We are excited to move forward under George’s leadership as we refine our strategic direction and implement several initiatives under development to strengthen the company for the future and drive sustainable growth and profitability.”',
            'Rob Lloyd, chief operating officer and chief financial officer, added, “We are pleased to have delivered fiscal 2018 results within our adjusted guidance range, which included fourth quarter and full year sales growth across video game accessories, collectibles and digital.  Excluding the impact of the 53rd week in fiscal 2017, new hardware sales for the year were in line with last year.  As we think about 2019 and beyond, we recognize the challenges facing our pre-owned video game business and are prepared to address them as we continue to evolve our business model going forward.  Importantly, we will continue to leverage our powerful brand to drive growth and, with a new cost savings and profit improvement initiative in place, we will focus our efforts on driving profitability. GameStop is a leader in the video game industry, and we remain committed to capitalizing on our leadership position to discover new and unique ways to meet our loyal customers’ entertainment needs and attract new customers.”',
        ],
        quarterOverviewPoints: [
            'As previously disclosed, the Company completed the sale of its Spring Mobile business on January 16, 2019 and the results of that business are included in discontinued operations for the fourth quarter and fiscal 2018 period.  Fiscal fourth quarter 2018 contained 13 weeks of operating results compared to 14 weeks in fiscal 2017.',
            'Total global sales from continuing operations decreased 7.6% (decreased 6.2% in constant currency) to $3.1 billion, resulting in a consolidated comparable store sales increase of 1.4% (3.4% increase in the U.S. and 2.9% decrease internationally).  The primary contributors to the difference between the increase in comparable store sales and the decrease in total company sales was the shift in the company’s fiscal calendar for the 53rd week in fiscal 2017 and the timing of the Call of Duty launch. ',
            'New hardware sales decreased 9.8%, with an increase in Nintendo Switch sales offset by a decline in Xbox One X sales due to its strong launch in the prior year and the impact of the 53rd week in fiscal 2017. ',
            'New software sales decreased 7.8%, driven by key titles launching earlier in the year compared to last year and the impact of the 53rd week in fiscal 2017. ',
            'Accessories sales increased 18.8% on the continued strength of controller and headset sales.',
            'Pre-owned sales declined 21.3% reflecting declines in hardware and software.',
            'Digital receipts increased 4.7% to $432.5 million, primarily driven by strength in sales of digital currency. ',
            'Collectibles sales increased 3.1% to $268.8 million, with continued growth in both domestic and international stores.',
            'GameStop’s fourth quarter GAAP net income (loss) was ($187.7) million, or ($1.84) per diluted share, compared to net income (loss) of ($105.9) million, or ($1.04) per diluted share, in the prior-year quarter.  Fourth quarter fiscal 2018 results include asset impairment charges and other items of $334.5 million ($351.6 million net of taxes), or $3.44 per diluted share, primarily related to impairment of goodwill.  Fourth quarter fiscal 2017 results included asset impairment charges and other items of $406.5 million ($310.9 million net of taxes), or $3.06 per diluted share, primarily related to impairment of intangible assets.',
            'Excluding the asset impairment charges and other items, GameStop’s adjusted net income from continuing operations for the fourth quarter decreased 16.2% to $148.5 million, compared to adjusted net income from continuing operations of $177.2 million in the prior-year quarter.  Adjusted earnings per diluted share from continuing operations were $1.45 compared to adjusted earnings per diluted share from continuing operations of $1.74 in the prior-year quarter.',
        ],
        yearOverviewPoints: [
            'Fiscal 2018 contained 52 weeks of operating results compared to 53 weeks in fiscal 2017.',
            'Total global sales from continuing operations decreased 3.1% to $8.3 billion, while consolidated comparable store sales decreased 0.3% (1.8% increase in the U.S. and 4.8% decrease internationally).',
            'Accessories sales increased 22.0%.',
            'Collectibles sales increased 11.2% to $707.5 million.',
            'Digital receipts increased 16.5% to $1.3 billion.',
            'New hardware sales declined 1.3%.',
            'New software sales declined 5.1%.',
            'Pre-owned sales declined 13.2%.',
            'Generated free cash flow of $232.7 million.',
        ],
    },
    {
        quarter: 'Q1',
        year: 2019,
        summaryPoints: [
            'George Sherman, GameStop’s chief executive officer said, “Since joining GameStop in April, I have been undertaking a thorough review of the business and working closely with the team to improve our operational and financial performance, address the challenges that have impacted our results, and execute both deliberately and with urgency.  We believe we will transform the business and shape the strategy for the GameStop of the future.  This will be driven by our go-forward leadership team that is now in place, a multi-year transformation effort underway, a commitment to focusing on the core elements of our business that are meaningful to our future, and a disciplined approach to capital allocation.”'
        ],
        quarterOverviewPoints: [
            'Total global sales decreased 13.3% (11.5% in constant currency) to $1.5 billion, resulting in a consolidated comparable store sales decrease of 10.3% (10.2% in the U.S. and 10.4% internationally).    ',
            'New hardware sales decreased 35.0%, with an increase in Nintendo Switch sales more than offset by a decline in Xbox One and PlayStation 4 console sales. ',
            'New software sales decreased 4.3%, driven by weaker new title launches in the quarter compared to last year. ',
            'Accessories sales increased 0.6% on the continued strength of controller sales.',
            'Pre-owned sales declined 20.3% reflecting declines in hardware and software.',
            'Digital receipts decreased 6.7% to $255.4 million, driven by weaker title launches in the quarter compared to last year.',
            'Collectibles sales increased 10.5% to $157.3 million, with continued growth in both domestic and international stores.',
            'GameStop’s first quarter GAAP net income was $6.8 million, or $0.07 per diluted share, compared to net income of $28.2 million, or $0.28 per diluted share, in the prior-year quarter, which included the Spring Mobile business.',
            'GameStop’s net income from continuing operations for the first quarter was $7.5 million or $0.07 per diluted share, compared to net income from continuing operations of $20.4 million, or $0.20 per diluted share, in the prior-year quarter.  First quarter fiscal 2018 net income included severance and other charges of $11.2 million ($9.7 million net of taxes).  First quarter fiscal 2018 adjusted net income from continuing operations was $30.1 million or $0.30 per diluted share.',
        ],
        yearOverviewPoints: [],
    },
    {
        quarter: 'Q2',
        year: 2019,
        summaryPoints: [
            'George Sherman, GameStop’s chief executive officer said, “We are committed to acting with a sense of urgency to address the areas of the business that are critical to achieving long-term success and value creation for all our stakeholders. We will set GameStop on the correct strategic path and  fully leverage our unique position and brand in the video game industry. Our strategic plan is anchored on four tenets which include, optimizing the core business by driving efficiency and effectiveness, creating the social and cultural hub of gaming within each GameStop, building compelling digital capabilities, and transforming our vendor and partner relationships for an evolving video game industry. This is a compelling new strategic vision for the company, and we’ve already started to execute against all four pillars. We also remain committed to returning capital to shareholders and balancing that opportunity against the need to maintain a strong balance sheet to properly run our business and invest in responsible growth.”',
            'As part of its go-forward plans, the company’s leadership outlined a strategy to improve the financial performance of the business and implement a series of initiatives that will support the long-term success of the business and value creation for stakeholders.',
            'Optimize the Core: Optimize the core business by improving efficiency and effectiveness across the organization, including cost restructuring, inventory management optimization, adding and growing high margin product categories, and rationalizing the global store base.',
            'Become the Social / Cultural Hub for Gaming: Create the social and cultural hub of gaming across the GameStop platform by testing and improving existing core assets including the store experience, knowledgeable associates and the PowerUp Rewards loyalty program.',
            'Build Digital Platform: Build compelling digital capabilities, including the recent relaunch of GameStop.com, to reach customers more broadly across the omni-channel platform and give them the full spectrum of content and access to products they desire.',
            'Transform Vendor Partnerships: Transform our vendor and partner relationships to unlock additional high-margin revenue streams and optimize the lifetime value of every customer.  '
        ],
        quarterOverviewPoints: [
            'Jim Bell, GameStop’s chief financial officer said, “While we experienced sales declines across a number of our categories during the quarter, these trends are consistent with what we have historically observed towards the end of a hardware cycle. We will continue to manage the underlying businesses to produce meaningful cash returns, while maintaining a strong balance sheet and investing responsibly in our strategic initiatives.”',
            'GameStop’s second quarter total global sales decreased 14.3% (13.1% in constant currency) to $1.3 billion, resulting in a consolidated comparable store sales decrease of 11.6%.    ',
            'New hardware sales decreased 41.1%, reflective of recent announcements for next generation console launches in 2020. ',
            'New software sales decreased 5.3%, with growth in Nintendo Switch software titles more than offset by weaker title launches across other consoles in the quarter compared to last year. ',
            'Accessories sales decreased 9.5%.',
            'Pre-owned sales declined 17.5% with declines in hardware and software.',
            'Digital receipts decreased 11.2% to $227.2 million due to weaker title launches in the quarter compared to last year.',
            'Collectibles sales increased 21.2%, with continued strong double-digit growth in both domestic and international stores.',
            'GameStop’s second quarter GAAP net income (loss) was ($415.3) million, or ($4.15) per diluted share, compared to net income (loss) of ($24.9) million, or ($0.24) per diluted share, in the prior-year quarter, which included the Spring Mobile business. Second quarter fiscal 2019 results include asset impairment charges and other items of $400.9 million ($381.6 million net of taxes), or $3.82 per diluted share, primarily related to impairment of goodwill. Second quarter fiscal 2018 results included a non-operating tax charge of $29.6 million, or $0.29 per diluted share.',
            'Excluding the $400.9 million of impairment charges and other items, GameStop’s adjusted net income (loss) from continuing operations for the second quarter was ($32.0) million or ($0.32) per diluted share, compared to net income (loss) from continuing operations of ($10.2) million, or ($0.10) per diluted share, in the prior-year quarter. ',
        ],
        capitalAllocationPoints: [
            'On July 10, 2019, GameStop completed a modified Dutch auction tender offer to purchase 12,000,000 shares of its common stock at $5.20 per share for an aggregate cost of $62.4 million, excluding fees and expenses. The company is committed to returning excess capital to shareholders as appropriate and currently has approximately $237 million remaining under the existing share repurchase authorization. During the quarter, the company reduced its outstanding debt by $49.8 million, bringing the year-to-date reduction in debt to $401.7 million with $419.1 million of long-term debt remaining on the balance sheet at quarter end. '
        ],
        yearOverviewPoints: [],
    },
    {
        quarter: 'Q3',
        year: 2019,
        summaryPoints: [
            'George Sherman, GameStop’s chief executive officer said, “Our third quarter results continue to reflect the prevailing industry trends, most notably the unprecedented decline in new hardware sales seen across the market as the current generation of gaming consoles reach the end of their lifecycle and consumers delay their spending in anticipation of new hardware releases. With console makers set to introduce new and innovative gaming consoles late next year, we anticipate this trend to continue until the fourth quarter of  2020.  Despite the current top-line trends, we are pleased with the continued strong progress that we are making against our strategic initiatives as we transform GameStop for the future.  We remain on track to achieve our $200 million annualized operating profit improvement goal, by 2021 and we believe our strategic initiatives will enable to us to achieve our long-term growth and profit objectives as we fully leverage our unique leadership position and brand in the video game space.”',
            'Mr. Sherman continued, “Since July, we have repurchased more than one-third of our outstanding shares, underscoring our continued conviction in the long-term value proposition of GameStop, our ability to execute on our strategic initiatives and deliver positive cash flows, as well as our commitment of returning capital to shareholders.”',
        ],
        quarterOverviewPoints: [
            'GameStop’s third quarter total global sales decreased 25.7% (24.7% in constant currency) to $1.4 billion, driven by a consolidated comparable store sales decrease of 23.2%.    ',
            'New hardware sales decreased 45.8%, reflecting anticipated next generation console launches in 2020. ',
            'New software sales decreased 32.6%, with growth in Nintendo Switch software titles more than offset by weaker title launches across other consoles in the quarter compared to last year. ',
            'Accessories sales decreased 13.4%.',
            'Pre-owned sales declined 13.3% with declines in hardware and software.',
            'Collectibles sales increased 4.3%, with continued growth in both domestic and international stores.',
            'GameStop’s third quarter GAAP net loss was ($83.4) million, or ($1.02) per diluted share, compared to net loss of ($488.6) million, or ($4.78) per diluted share, in the prior-year quarter, which included the Spring Mobile business.  Third quarter fiscal 2019 results include charges of $43.0 million, or $0.52 per diluted share, which included non-cash asset impairment charges, tax adjustments, transformation costs and other items.  Third quarter fiscal 2018 results included non-operating, non-cash intangible asset impairment charges of $587.5 million, primarily related to goodwill.',
            'Excluding the $43.0 million of impairment charges and other items, GameStop’s adjusted net loss from continuing operations for the third quarter was ($40.2) million or ($0.49) per diluted share, compared to net income from continuing operations of $50.0 million, or $0.49 per diluted share, in the prior-year quarter. ',
        ],
        capitalAllocationPoints: [
            'During the quarter, the company repurchased 22.6 million shares of its common stock, for $115.7 million, or an average price of $5.11 per share, bringing the year-to-date repurchase activity to $178.6 million for 34.6 million shares, or 34% of the shares outstanding, at an average price of $5.14 per share.  As of the end of the fiscal third quarter, the company had 67.8 million shares outstanding.  The company remains committed to opportunistically returning excess capital to shareholders as it continues to execute on its strategic initiatives to position the Company for the long term.',
            'As previously disclosed, during fiscal 2019, the company has reduced its outstanding debt by $401.7 million and has $419.4 million of long-term debt remaining on the balance sheet at quarter end. ',
        ],
        yearOverviewPoints: [],
    },
    {
        quarter: 'Q4',
        year: 2019,
        summaryPoints: [
            'Generated $62.3 million in adjusted operating income while exiting the year with approximately $500 million in cash, despite a challenging sales environment. ',
            'Significantly improved capital structure, deploying proceeds from sale of non-core business units to reduce debt by $401 million, repurchase 38.1 million shares for $199 million to leverage the Company’s market position as the pure-play, omni-channel leader in gaming.',
            'Optimized operations by improving inventory with a 31% reduction at year end and implementing initiatives to accelerate GameStop’s transformation with initiatives in digital, online, experiential retail and its loyalty program and continuing to de-densify the store base. ',
            'Began fiscal 2020 with increased financial flexibility and continued focus on key priorities to optimize, stabilize and  transform GameStop to achieve sustainable profitable long-term growth.',
            'George Sherman, GameStop’s chief executive officer, said, “We delivered profitability, on an adjusted basis, ahead of our updated expectations, marking progress on our strategy to evolve our operating model and position GameStop for long-term profitable growth. We accomplished this, despite industry challenges that led to an expected significant decline in sales. Financially, we improved efficiency and effectiveness across our enterprise during the year fueling a 160 basis point expansion in gross margin and a $130 million reduction in adjusted SG&A. We strengthened the balance sheet, including significant reductions in inventory, accounts payable and debt. Operationally, we accelerated our digital capabilities by elevating our web platform and further optimizing our retail footprint through market de-densification while setting up a laboratory in our Tulsa market to test experiential elements in 12 stores with promising initial results.”',
            'Mr. Sherman, continued, “As we begin fiscal 2020, we remain focused on our key priorities, yet recognize that we continue to face the temporary headwind of lower current generation console hardware and software sales as consumers delay purchases in anticipation of new platform launches expected later in the year.  The COVID-19 outbreak has led to changes in how consumers work, play and learn and over the past few weeks, led to increased demand for our products.  While still early, we are pleased with the progress we have made to date in our initiatives to stabilize, optimize and transform the business, specifically the strengthening of our balance sheet.  As such, we will maintain our focus on expense and inventory discipline so that we move forward with a strengthened platform to capitalize on the significant opportunities we see for growth.” ',
        ],
        quarterOverviewPoints: [
            'Total global comparable store sales decreased 26.1%',
            'Gross margin expanded 280 bps from the prior year fourth quarter',
            'SG&A was $511.7 million compared to $552.5 million in the prior year fourth quarter',
            'Adjusted SG&A was $488.1 million, a reduction of $58.2 million from the prior year fourth quarter',
            'Operating income of $75.2 million compared to operating loss of ($232.1) million in the prior year fourth quarter',
            'Adjusted operating income of $109.2 million compared to adjusted operating income of $202.5 million in the prior year fourth quarter',
            'Net income of $21.0 million, or $0.32 per diluted share compared to net loss of ($187.7) million, or a loss of (1.84) per diluted share in the prior year fourth quarter',
            'Adjusted net income of $83.8 million or $1.27 per diluted share, compared to adjusted net income of $148.5 million, or $1.45 per diluted share in the prior year fourth quarter',
            'Repurchased 3.5 million shares of common stock for $20.1 million',
        ],
        capitalAllocationPoints: [
            'During the quarter, the Company repurchased 3.5 million shares of its common stock, for $20.1 million, or an average price of $5.74 per share, bringing the fiscal 2019 repurchase activity to $199 million for 38.1 million shares, or 37% of the shares outstanding, at an average price of $5.21 per share. As of the end of the fourth quarter, the Company had 64.3 million shares outstanding.  During fiscal 2019, the Company reduced its outstanding debt by $401.0 million and had $419.8 million of long-term debt remaining on the balance sheet at fiscal year-end.'
        ],
        yearOverviewPoints: [
            'Total global comparable store sales decreased 19.4%',
            'Gross margin expanded 160 bps from the prior year',
            'SG&A was $1.923 billion compared to $1.994 billion from the prior year',
            'Adjusted SG&A was $1.846 billion, a reduction of $130.4 million from the prior year',
            'Operating loss of ($399.6) million compared to operating loss of ($702.0) million in the prior year',
            'Adjusted operating income of $62.3 million compared to adjusted operating income of $331.3 million in the prior year',
            'Net loss of ($470.9) million, or ($5.38) per diluted share compared to net loss of ($673.0) million, or ($6.59) per diluted share in the prior year',
            'Adjusted net income of $19.1 million or $0.22 per diluted share compared to adjusted net income of $218.4 million, or $2.14 per diluted share in fiscal 2018',
            'Repurchased 38.1 million shares of common stock for $199 million',
        ],
    },
    {
        quarter: 'Q1',
        year: 2020,
        summaryPoints: [
            'First Quarter Net Sales of $1.021 billion; ',
            'Comparable Store Sales Declined 17% Excluding Stores Closed Due to COVID-19 with Majority of Locations Limited to Curbside Pickup',
            'First Quarter E-commerce Sales Increased 519%; Increased over 1,000% During the Six Weeks Following Store Closures Due to COVID-19',
            'Ends First Quarter with $570 million in Cash, Inventory Reduction of 43% and Accounts Payable Decline of 54% Compared to the First Quarter of Fiscal 2019',
            'George Sherman, GameStop’s chief executive officer said, “During this unprecedented time, our priority is focused on ensuring the safety and well-being of our employees, customers and business partners as we continue the process of opening our stores as restrictions are lifted, in our ongoing effort to meet our customers’ needs.  We are proud of our team’s ability to quickly adapt to meet the increased demand for our product offerings.  As the pandemic spread, we leaned in on our upgraded omni-channel capabilities to fulfill customer orders through curbside pick-up where available, we reduced discretionary spending and enhanced our liquidity while continuing to advance our strategic priorities.  While we delivered a loss for the quarter in total, our performance included total sales just shy of our original expectations, even as stores closed due to the COVID-19 pandemic and key video game titles shifted to the second and third quarters, exacerbating the headwind from operating in the final stage of a console cycle.  Even more impressive is that our e-commerce sales grew 519% in the first quarter and over 1,000% during the six weeks that our store base temporarily closed to customer access.  We believe this reflects the loyalty of the GameStop customer and the confidence they place in us as their preferred place to shop.” ',
            'Mr. Sherman, continued, “Importantly, we continued to make progress on our strategic initiatives.  We continued to optimize the core business operation and maintained financial strength and flexibility, recording a 43% decline in inventory and a 54% decrease in accounts payable compared to last year.  Additionally, we saw significant progress towards building a frictionless digital ecosystem as evidenced by our successful omni-channel activities, including improved fulfillment capabilities as we utilized our stores as distribution centers and for curbside pick-up, which in most cases supported same day delivery to the customer.”',
            'Mr. Sherman, concluded, “As we begin the second quarter, we are cautiously and prudently navigating the near-term, as we are operating in the last few months of the current generation console cycle and believe we have experienced a pull forward in demand for end-of-life inventory given a surge in gaming product demand following the global stay-at-home orders.  That said, we believe the performance we achieved despite multiple headwinds is further evidence of the power of GameStop and the advantages that we possess driven by our global footprint, knowledgeable sales associates and strong loyalty base.  We believe these attributes along with our intense focus on expense and working capital management have us poised to capitalize on the hardware and software sales growth expected as several new software titles and next generation consoles are introduced later this year.”     ',

        ],
        quarterOverviewPoints: [
            'As previously announced, on March 22, 2020, the Company temporarily closed all 3,526 of its U.S. locations – with approximately 65% of these locations conducting a limited curbside pickup offering.  During the final six-weeks of the fiscal first quarter, approximately 90% of the global store fleet was closed to customer access and only Australia, which represents approximately 10% of the global store count, remained fully open and accessible to customers, approximately 42% remained open for limited curbside delivery and 48% remained fully closed.  In Australia, where all stores remained open for business during the first quarter, increased demand drove a 35% comparable store sales increase.    ',
            'Total global comparable store sales decreased 17% excluding stores that were closed during the first quarter as a result of the COVID-19 pandemic.  After including the impact of stores that were closed for the majority of the quarter due to the COVID-19 pandemic, comparable stores sales decreased by approximately 30%.',
            'Global E-commerce sales increased 519% compared to the prior year first quarter, despite having severely limited distribution operations across international businesses.',
            'Gross margin declined 270 bps from the prior year first quarter, driven by the increased mix of hardware compared to the prior year first quarter.',
            'SG&A was $386.5 million, down $67.2 million or 15% compared to $453.7 million in the prior year first quarter which includes $18.5 million in incremental wages paid to hourly associates to help offset lost wages due to store closures from the COVID-19 pandemic, and approximately $3.0 million in incremental costs associated with safety materials and equipment to ensure the safety of customers and associates.',
            'Adjusted SG&A was $381.2 million, a reduction of $72.5 million, or 16% from the prior year first quarter.',
            'Operating loss of ($108.0) million compared to operating earnings of $17.5 million in the prior year first quarter.',
            'Adjusted operating loss of ($98.8) million compared to adjusted operating income of $17.5 million in the prior year first quarter.',
            'Net loss of ($165.7) million, or ($2.57) per diluted share, including a $53.0 million non-cash tax charge associated with the valuation allowance against deferred tax assets, an additional $18.5 million in incremental wages paid to our hourly associates to help offset lost wages due to store closures from the COVID-19 pandemic, and approximately $3.0 million in incremental costs associated with safety materials and equipment to ensure the safety of our customers and associates, compared to net income of $6.8 million, or earnings per share of $0.07 per diluted share in the prior year first quarter.',
            'Adjusted EBITDA of ($75.5) million compared to $42.7 million in the prior year first quarter.',
            'Adjusted net loss of ($103.9) million or ($1.61) per diluted share, compared to adjusted net income of $7.5 million, or $0.07 per diluted share in the prior year first quarter.',
        ],
        capitalAllocationPoints: [
            'As of May 2, 2020, the Company had approximately $570 million in total cash, reflecting $135 million drawn under its revolving credit facility.  As of June 3, 2020, the Company had reduced its outstanding borrowings under the facility to approximately $100 million.  The Company continues to expect it will have sufficient liquidity and financial flexibility to fund its operations and navigate the current environment. Given effective working capital management, the Company expects to have total cash and liquidity between $575 million and $625 million as of the end of its second fiscal quarter.',
            'As of May 2, 2020, the Company had $417.2 million of debt on the balance sheet and on June 4, 2020, the Company announced an exchange offer and consent solicitation for the remaining unsecured notes due to mature in March 2021.  The new notes, if issued, will provide additional financial flexibility by replacing and extending the maturity of the existing notes validly tendered in the exchange offer until 2023.  There can be no assurance that the exchange offer and consent solicitation will be consummated on the contemplated terms, or at all.',
        ],
    },
    {
        quarter: 'Q2',
        year: 2020,
        summaryPoints: [
            'Global E-commerce Sales Increase 800%',
            'SG&A Improves by $133.7 million',
            'Generates Cash Flow From Operations of $192.8 million And Free Cash Flow of $181.9 million',
            'George Sherman, GameStop’s chief executive officer, said, “The second quarter saw strong progress toward our strategic initiatives, fueling an 800% increase in global E-commerce sales, a $133.7 million reduction in SG&A and a significant improvement in our balance sheet with $735.1 million in cash at quarter-end and a 50% reduction in inventory, as compared to the second quarter last year.  These achievements combined drove $181.9 million in free cash flow for the quarter. I am extremely proud of our team, and their dedication to our mission, our strategy and safely serving our customers despite operating in an unprecedented environment.”',
            '“We believe the actions we are taking to optimize the core operations of our business by increasing efficiencies and creating a frictionless digital ecosystem to serve our customers, wherever and whenever they choose to shop, are enabling us to navigate the COVID-19 environment while positioning us well for the launch of the next generation of consoles.” ',
            'Mr. Sherman continued, “While the ongoing pandemic continues to create a somewhat uncertain environment in the short term, we are very pleased by the consumer response at GameStop to the few recent video game product introductions and we believe we are ready, with expanded service and payment options, to handle the expected surge in demand and participate in a very significant way in the console launches later this year.”',
        ],
        quarterOverviewPoints: [
            'Net sales were $942.0 million, down 26.7% from the fiscal 2019 second quarter reflecting: ',
            'The impact of operating during the last few months of the seven-year-long current generation console cycle and the subsequent limited availability of hardware and accessories;',
            'A 13% reduction in total store operating days due to temporary store closures driven by the global COVID-19 pandemic; and',
            'A 10% reduction in the store base, as part of the Company’s de-densification strategy, partially offset by almost  40% of closed store sales recaptured through the transfer to neighboring locations and online, leading to improved cash flow.',
            'Comparable store sales declined 12.7%, adjusting for fewer store operating days due to store closures as a result of the global COVID-19 pandemic.',
            'Global E-commerce sales rose 800% and are included in comparable store sales.',
        ],
        capitalAllocationPoints: [
            'As of August 1, 2020, the Company had $735.1 million in total cash and reduced its outstanding borrowings under the asset based revolving credit facility to $35 million. ',
            'As of August 1, 2020, the Company had $256.3 million of short-term debt and $215.9 million of long-term debt on the balance sheet. As previously announced on July 2, 2020, the Company completed the exchange offer and consent solicitation for $216.4 million of unsecured notes, reducing the amount due to mature in March 2021 to approximately $198 million.  The newly issued notes provide additional financial flexibility by replacing and extending the maturity of the existing notes to 2023. ',
        ],
    },
    {
        quarter: 'Q3',
        year: 2020,
        summaryPoints: [
            'Omni-channel Capabilities Fuel 257% Increase in Global E-Commerce Sales',
            'Operating Platform Optimization Drives $115 million, or 24% SG&A Improvement',
            'GRAPEVINE, Texas, Dec. 08, 2020 (GLOBE NEWSWIRE) --  GameStop Corp. (NYSE: GME) today reported results for the third quarter ended October 31, 2020 that reflect sustained progress toward its long-term strategic objectives and a positive start to the fourth fiscal quarter following the launch of the long-awaited next generation of video game consoles.',
            'George Sherman, GameStop’s chief executive officer, said, “Our third quarter results were in-line with our muted expectations and reflected operating during the last few months of a seven-year console cycle and a global pandemic, which pressured sales and earnings.  That notwithstanding, we continued to significantly advance our strategic objectives of creating a digital-first, omni-channel ecosystem for games and entertainment and optimizing our core operations.  Leveraging our omni-channel capabilities, we increased E-Commerce sales 257% – demonstrating our ability to serve our customers, wherever, whenever and however they choose to shop. Investments in improving our web properties and mobile app and enhanced fulfillment capabilities contributed to our E-Commerce channel’s sales contribution rising to nearly 25% year to date, well-above historical mid-single digit levels.  Moreover, as the result of our ongoing optimization of expenses, stores and inventory, we delivered a $316 million reduction in SG&A expenses through the third quarter, ending the period with $603 million cash and restricted cash after repaying $10 million in debt during the quarter, and saw a 33% reduction in inventory compared to the prior year.”',
            '“We begin the fourth quarter with unprecedented demand in new video game consoles that launched in November, which drove a 16.5% increase in comparable store sales for the month, despite being closed on Thanksgiving Day and the impact of COVID-19 related store closures, which affected most of our European footprint. We anticipate, for the first time in many quarters, that the fourth quarter will include positive year-on-year sales growth and profitability, reflecting the introduction of new gaming consoles, our elevated omni-channel capabilities and continued benefits from our cost and efficiency initiatives, even with the potential further negative impacts on our operations due to the global COVID-19 pandemic.  Overall, we remain confident in our strategy and look forward to executing in 2021 on the many exciting opportunities to leverage our brand, extensive loyalty member base, and increased digital capabilities to expand our addressable market and product offerings, providing growth in all things games and entertainment,” Sherman concluded.',
        ],
        quarterOverviewPoints: [
            'Net sales were $1,004.7 million, down 30.2% from the fiscal 2019 third quarter reflecting: ',
            'The impact of operating during the last few months of the seven-year-long current generation console cycle and the subsequent limited availability of hardware and accessories;',
            'The unplanned shift of software titles later into the fourth fiscal quarter, and in some cases, into fiscal 2021;',
            'An 11% reduction in the store base, as part of the Company’s de-densification strategy, partially offset by recaptured sales through the transfer to neighboring locations and online',
            'Comparable store sales declined 24.6%',
            'Global E-Commerce sales increased 257% and are included in comparable store sales',
        ],
        capitalAllocationPoints: [
            'As of October 31, 2020, the Company had $602.6 million in cash and restricted cash compared to $304.4 million in cash and restricted cash in the prior year third quarter. The Company reduced its outstanding borrowings under the asset based revolving credit facility to $25 million. ',
            'As of October 31, 2020, the Company had $269.5 million of short-term debt and $216.0 million of long-term debt on the balance sheet. Subsequent to quarter end, as previously announced on November 10, 2020, the Company announced the voluntary early redemption of $125 million in principal amount of its 6.75% senior notes due 2021, on December 11, 2020. This voluntary early redemption covers approximately 63% of the outstanding Notes. The voluntary early redemption is consistent with the Company’s strategy to strengthen and enhance its balance sheet, improve its debt profile, and optimize its capital structure. ',
            'As part of its strategies to create optimal financial flexibility and expand liquidity alternatives, the Company intends to file a shelf registration and prospectus supplement with the Securities and Exchange Commission today under which it may offer and sell, from time to time, shares of its Class A common stock in “at-the-market offerings.” Net proceeds from sales of shares under the  “at-the-market” program, if any, would be used for working capital and general corporate purposes, which may include funding of the Company’s ongoing digital-first omni-channel growth strategy and expansion of its product and services offering.  The timing and amount of sales of shares, if any, will depend on a variety of factors, including prevailing market conditions, the trading price of shares, and other factors as determined by the Company.',
            'Jim Bell, GameStop’s chief financial officer, said, “As we continue to optimize our business model, we are shifting focus to execute the transformational components of our strategy that will position GameStop to be a leading omni-channel retailer for all things games and entertainment, which we believe will lead to sustained long-term profitable growth.  Over the past 18 months, we have remained steadfast in focusing on creating a more efficient business model. These efforts, despite the impacts of a global pandemic, have led to a stronger balance sheet. We believe the shelf registration and associated at-the-market program, if we chose to use it, provide us further options to enhance our liquidity alternatives to support an efficient and successful execution of our transformational strategies.”',
        ],
    },
    {
        quarter: 'Q4',
        year: 2020,
        summaryPoints: [
            'Achieved 6.5% Increase in Comparable Store Sales During Fourth Quarter, With Global E-Commerce Sales Increasing 175% for the Fourth Quarter and 191% for Fiscal 2020',
            'Expense Reduction Initiatives Drove $409 Million, or 21%, SG&A Improvement in Fiscal 2020',
            'Strengthened the Balance Sheet and Ended Fiscal 2020 With $635 Million in Total Cash, Laying the Foundation for Transformation',
            'Announces the Appointment of Technology Veteran Jenna Owens as New Chief Operating Officer',
        ],
        quarterOverviewPoints: [
            'Comparable store sales increased 6.5%; ',
            'Net sales were $2.122 billion compared to $2.194 billion in the fiscal 2019 fourth quarter, reflecting an operating environment that included a 12% decrease in the store base due to the Company’s strategic de-densification efforts and a reduction of approximately 27% in European store operating days during the quarter as a result of temporary store closures in response to the COVID-19 pandemic;',
            'Global E-Commerce sales (included in comparable store sales) increased 175% and represented 34% of net sales in the fiscal 2020 fourth quarter versus 12% of net sales in the fiscal 2019 fourth quarter; ',
            'Gross margin was 21.1%, a decline of 610 basis points compared to the fiscal 2019 fourth quarter, reflecting an expected mix shift toward lower margin console sales in response to the launch of generation 9 consoles, increased freight and credit card fees associated with the shift to E-Commerce sales, and a broader promotional stance; ',
            'Selling, general and administrative expenses were $419.1 million, a decline of $92.6 million, or 18%, from $511.7 million in the fiscal 2019 fourth quarter, driven by the Company’s cost optimization initiatives;',
            'Income tax expense was a benefit of $69.7 million due to a change in the tax status of certain foreign entities, and the impact of the CARES Act, including tax benefits associated with the availability of a five-year carryback period for certain current year tax losses (which compares to income tax expense of $43.8 million in the fiscal 2019 fourth quarter), and; ',
            'Net income was $80.5 million, or $1.19 per diluted share on 67.8 million shares outstanding and included a $1.03 per share tax benefit as described above, as compared to diluted earnings per share of $0.32 in the fiscal 2019 fourth quarter.   Adjusted net income was $90.7 million or $1.34 per diluted share, compared to adjusted net income of $83.8 million or $1.27 per diluted share in the prior year fourth quarter.',
        ],
        capitalAllocationPoints: [
            'As of January 30, 2021, the Company had $635 million in cash and restricted cash compared to $513.5 million in cash and restricted cash in the prior year. The Company’s outstanding borrowings under its asset-based revolving credit facility were $25 million, which were subsequently repaid as of March 15, 2021.',
            'As of January 30, 2021, the Company had $146.7 million of short-term debt and $216.0 million of long-term debt on its balance sheet. During the fourth quarter, as previously announced on November 10, 2020, the Company announced the voluntary early redemption of $125 million in principal amount of its 6.75% senior notes due 2021, on December 11, 2020. On March 15, 2021, the Company fully redeemed the remaining $73.2 million of its 6.75% senior notes due 2021, reflecting the Company’s strategy to strengthen its balance sheet, improve its debt profile and optimize its capital structure.   ',
            'As of March 15, 2021, following the pay down of outstanding borrowings under the Company’s asset-based revolving credit facility and the redemption of its 6.75% senior notes due in 2021, the Company had $48.5 million of short-term debt and $216.0 million of long-term debt remaining on its balance sheet.',
        ],
        yearOverviewPoints: [
            'Comparable store sales decreased 9.5%;',
            'Net sales were $5.090 billion compared to $6.466 billion in fiscal 2019, reflecting an operating environment that included the impact of operating during the wind-down of the seven-year-old prior console cycle, a 12% decrease in the store base due to the Company’s strategic de-densification efforts, which was partially offset by recaptured sales via nearby stores and E-commerce, and a significant reduction in global store operating days as a result of temporary store closures in response to the COVID-19 pandemic at various times throughout the year;',
            'Global E-Commerce sales (included in comparable stores sales) increased 191% increase for the fiscal year and represented nearly 30% of total net sales;',
            'Gross margin was 24.7%, a decline of 480 basis points compared to the prior year primarily driven by the expected mix shift toward lower margin console sales in response to the launch of generation 9 consoles, increased freight and credit card fees associated with the shift to E-Commerce sales and a broader promotional stance;',
            'Selling, general and administrative expenses were $1.514 billion compared to $1.923 billion from the prior year, a reduction of $408.5 million, or 21.2% from the prior fiscal year;   ',
            'Income tax in fiscal 2020 was a benefit of $55.3 million driven by a change in the tax status of certain foreign entities and the impact of the CARES Act, including tax benefits associated with the availability of a five-year carryback period for certain current year tax losses, compared to income tax expense of $37.6 million in the prior fiscal year;',
            'Net loss of ($215.3) million, or ($3.31) per diluted share compared to net loss of ($470.9) million, or ($5.38) per diluted share in the prior fiscal year. Adjusted net loss of ($138.8) million or ($2.14) per diluted share compared to adjusted net income of $19.1 million or $0.22 per diluted share in fiscal 2019, and;',
            'Delivered a $408.5 million, or a 21.2% reduction in SG&A expense in fiscal 2020 compared to fiscal 2019, primarily driven by continued cost optimization initiatives',
            'Strategically de-densified the Company’s store base by closing a net 693 stores in fiscal 2020 while transferring sales to online platforms and neighboring locations;',
            'Achieved 30% decrease in inventory at fiscal year-end, leading to annualized inventory turns of 5.9x as compared to 4.4x in the prior year, and a 10% decrease in accounts payable at fiscal year-end as compared to fiscal 2019. ',
            'Ended fiscal 2020 with $635 million of cash and restricted cash;',
            'Reduced overall debt by $57 million, including a $125 million voluntary redemption of the Company’s 6.75% senior notes due 2021;   ',
            'Completed exchange offer and consent solicitation for $216.4 million of unsecured notes;',
            'Completed five sale leaseback transactions related to office buildings and the sale of a corporate travel asset, contributing approximately $95.5 million towards total liquidity, and;            ',
            'Completed the wind down of operations in Denmark, Finland, Norway and Sweden.',
            'George Sherman, GameStop’s chief executive officer, said, “I am proud of how our entire organization came together in 2020 to adapt to the challenging pandemic environment, effectively serve our customers’ demand for gaming and entertainment products, and navigate through the year with strong liquidity and a strengthened balance sheet. Our execution led to a profitable fourth quarter that included a 6.5% comparable store sales growth, a 175% increase in global E-Commerce sales and a $92.6 million reduction in SG&A. The past year also saw us take steps to accelerate our de-densification efforts and streamline our store footprint, leverage our retail locations to provide same-day delivery and curbside pickups, and continue to enhance our suite of E-Commerce platforms. We also added important experience to our board by appointing several new directors with backgrounds in corporate finance, E-Commerce and technology and subsequently established a strategy-focused committee to accelerate our transformation.”',
            '“We are off to a strong start in 2021 as February comparable store sales increased 23%, led by continued strength in global hardware sales. As we look ahead, we are excited by the opportunities that are in front of us as we begin prioritizing long-term digital and E-Commerce initiatives while continuing to execute on our core business during this emerging console cycle. Our emphasis in 2021 will be on improving our E-Commerce and customer experience, increasing our speed of delivery, providing superior customer service and expanding our catalogue,” Sherman concluded.',
        ],
    },
    {
        quarter: 'Q1',
        year: 2021,
        summaryPoints: [
            'Net Sales Grew 25% to $1.3 Billion',
            'Appoints Technology Veterans Matt Furlong and Mike Recupero to CEO and CFO Positions, Respectively ',
        ],
        quarterOverviewPoints: [
            'Net sales increased 25.1% to $1.277 billion, compared to $1.021 billion in the fiscal 2020 first quarter, overcoming a nearly 12% reduction in the Company’s global store base due to strategic de-densification efforts, and continued store closures across Europe due to the COVID-19 pandemic; ',
            'Gross margin was 25.9%, a decline of 180 basis points compared to the fiscal 2020 first quarter; ',
            'Reported selling, general and administrative expenses were $370.3 million, a decline of $16.2 million, or 4.2%, from $386.5 million in the fiscal 2020 first quarter. Adjusted for severance, transformation and other costs, selling, general and administrative expenses were $351.7 million, a decline of $29.5 million, or 7.7%, from $381.2 million in the fiscal 2020 first quarter;',
            'Operating loss of ($40.8) million compared to ($108.0) million in the fiscal 2020 first quarter. Adjusted operating loss of ($21.6) million compared to ($98.8) million in the fiscal 2020 first quarter;',
            'Net loss of ($66.8) million, or ($1.01) per diluted share as compared to net loss of ($165.7) million, or ($2.57) per diluted share, in the fiscal 2020 first quarter. Adjusted net loss of ($29.4) million or ($0.45) per diluted share, compared to adjusted net loss of ($157.6) million or ($2.44) per diluted share in the fiscal 2020 first quarter;',
            'Adjusted EBITDA of ($0.7) million compared to ($75.5) million in the fiscal 2020 first quarter, and;',
            'Income tax expense was $1.3 million compared to income tax expense of $50.4 million in the fiscal 2020 first quarter.  ',
        ],
        capitalAllocationPoints:[
            'As of May 1, 2021, the Company had $770.8 million in cash and restricted cash, compared to $583.9 million in cash and restricted cash in the prior year. The Company had no borrowings under its asset-based revolving credit facility and no long-term debt.',
            'On April 26, 2021, the Company announced it raised approximately $551.7 million in net proceeds through the issuance of 3.5 million shares of common stock under its “at-the-market” equity offering program, resulting in total shares outstanding of approximately 71.9 million. The Company has used and intends to continue using net proceeds to accelerate GameStop’s transformation as well as for general corporate purposes and further strengthening the balance sheet.',
            'On April 30, 2021, the Company completed its voluntary early redemption of $216.4 million in principal amount of its 10.0% Senior Notes due 2023 on April 30, 2021. This voluntary early redemption covered the entire amount of the outstanding 10.0% Senior Notes, which represented all of the Company’s long-term debt.',
            'In addition, the Company intends to file with the U.S. Securities and Exchange Commission a prospectus supplement to the base prospectus included in the Company’s shelf registration statement on Form S-3 (File No. 333-251197) under which the Company may offer and sell up to 5 million shares of its common stock, from time to time, in “at-the-market” offerings. The Company intends to use net proceeds for general corporate purposes as well as for investing in growth initiatives and maintaining a strong balance sheet. The timing and amount of any sales of shares, if any, will depend on a variety of factors, including prevailing market conditions, the trading price of shares and other factors as determined by the Company.',
        ],
        corporateUpdatePoints:[
            'GameStop today announced the appointments of Matt Furlong as Chief Executive Officer and Mike Recupero as Chief Financial Officer. Messrs. Furlong and Recupero join from Amazon, where they held senior roles and oversaw various growth initiatives during their respective tenures. The Company is continuing to actively pursue senior talent with gaming, retail and technology experience.',
        ]
    },
    {
        quarter: 'Q2',
        year: 2021,
        summaryPoints: [
            'Generated net sales of $1.183 billion, compared to $942 million in the prior year’s second quarter.',
            'Ended the period with cash and restricted cash of $1.78 billion. ',
            'Ended the period with no long-term debt, other than a $47.5 million low-interest loan associated with the French government’s pandemic response. ',
            'Invested in long-term growth initiatives that include expanding the Company’s product catalog, enhancing its fulfillment network capabilities and technology, and adding talent across the organization. ',
            'Entered into a lease of a new 530,000 square foot fulfillment center in Reno, Nevada, positioning the Company’s fulfillment network to span both coasts of the continental U.S. ',
            'Entered into a lease of a new customer care center in Pembroke Pines, Florida and started building out U.S.-based customer care operations.',
        ],
        quarterOverviewPoints: [],
    },
    {
        quarter: 'Q3',
        year: 2021,
        summaryPoints: [
            'Net sales were $1.297 billion for the quarter, compared to $1.005 billion in the prior year’s third quarter. ',
            'Sales attributable to new and expanded brand relationships, such as Samsung, LG, Razer, Vizio and others, contributed to the Company’s growth in the quarter. ',
            'Inventory was $1.141 billion at the close of the quarter, compared to $861 million at the close of the prior year’s third quarter, reflecting the Company’s focus on front-loading investments in inventory to meet increased customer demand and mitigate supply chain issues. ',
            'Ended the period with cash and cash equivalents of $1.413 billion as well as no debt other than a $46.2 million low-interest, unsecured term loan associated with the French government’s response to COVID-19. ',
            'Established new offices in Seattle, Washington and Boston, Massachusetts, which are technology hubs with established talent markets. ',
            'Secured a new $500 million ABL facility, which closed in November just after the end of the third quarter, with improved liquidity and terms, including reduced borrowing costs, lighter covenants and additional flexibility. ',
        ],
        quarterOverviewPoints: [], 
    },
    {
        quarter: 'Q4',
        year: 2021,
        summaryPoints: [],
        quarterOverviewPoints: [
            'Generated net sales of $2.254 billion for the quarter, compared to $2.122 billion in the fourth quarter of 2020 and $2.194 billion in the fourth quarter of 2019. ',
            'Established new and expanded brand relationships, including with PC gaming companies such as Alienware, Corsair and Lenovo, that contributed to sales growth in the quarter. ',
            'Grew PowerUp Rewards Pro members by 32% on a year-over-year basis, taking total membership to approximately 5.8 million. ',
            'Entered into a partnership with Immutable X that is intended to support the development of GameStop’s NFT marketplace and provide the Company with up to $150 million in IMX tokens upon achievement of certain milestones. ',
            'Launched a redesigned app, which includes an enhanced user interface, improved scalability for a larger product catalog and more functionality to support exclusive offers and promotions. ',
            'Hired dozens of additional individuals with experience in areas such as blockchain gaming, ecommerce and technology, product refurbishment and operations. ',
        ],
        yearOverviewPoints:[
            'Generated net sales of $6.011 billion for the fiscal year, compared to $5.090 billion for fiscal year 2020. ',
            'Expanded the product catalog to include a broader set of consumer electronics, PC gaming equipment and refurbished hardware. ',
            'Made significant and long-term investments in the Company’s fulfillment network, systems and teams. ',
            'Established new offices in Seattle, Washington and Boston, Massachusetts, which are technology hubs with established talent markets. ',
            'Raised more than $1.67 billion in capital and eliminated all of the Company’s long-term debt, other than a $44.6 million low-interest, unsecured term loan associated with the French government’s response to COVID-19. ',
            'Ended the fiscal year with $1.271 billion in cash and cash equivalents and $915 million in inventory, compared to $635 million in cash and $602.5 million in inventory at the end of fiscal year 2020. Increased investments in inventory reflect the Company’s focus on meeting heightened demand and mitigating supply chain headwinds. ',
        ]
    },
    {
        quarter: 'Q1',
        year: 2022,
        summaryPoints: [
            'Net sales were $1.378 billion for the quarter, compared to $1.277 billion in the prior year’s first quarter. ',
            'Sales attributable to new and expanded brand relationships contributed to the Company’s growth in the quarter. ',
            'Inventory was $917.6 million at the close of the quarter, compared to $570.9 million at the close of the prior year’s first quarter, reflecting a continued focus on improving in-stock levels in merchandise to meet increased customer demand and offset supply chain headwinds. ',
            'Ended the period with cash and cash equivalents of $1.035 billion as well as no debt other than a low-interest, unsecured term loan associated with the French government’s response to COVID-19. ',
            'Took steps to support the recent launch of a digital asset wallet to allow gamers and others to store, send, receive and use cryptocurrencies and non-fungible tokens (“NFTs”) across decentralized apps. The wallet extension will enable transactions on GameStop’s NFT marketplace upon its intended launch in the second quarter. ',
            'Continued hiring individuals with experience in areas such as blockchain gaming, ecommerce and technology, and operations, including a new Chief Operating Officer with a background in retail and stores. '
        ],
        quarterOverviewPoints: [],
    },
    {
        quarter: 'Q2',
        year: 2022,
        summaryPoints: [
            'Net sales were $1.136 billion for the quarter, compared to $1.183 billion in the prior year’s second quarter. ',
            'Sales attributable to collectibles, which is a segment the Company intends to grow over the long-term, were $223.2 million for the quarter, compared to $177.2 million in the prior year’s second quarter. ',
            'Selling, general and administrative expenses were $387.5 million for the quarter, representing a sequential decline of 14.3% from the first quarter of 2022 and reflecting, in part, the Company’s focus on right-sizing costs following a period of significant investment in long-term initiatives. ',
            'Inventory was $734.8 million at the close of the quarter, compared to $596.4 million at the close of the prior year’s second quarter, reflecting the Company’s focus on maintaining adequate in-stock levels to meet customer demand and offset lingering supply chain headwinds. ',
            'Followed the launch of the Company’s digital wallet by launching the Company’s non-fungible token ("NFT") marketplace to allow gamers, creators, collectors and others to buy, sell and trade NFTs. ',
            'Modernized and strengthened the Company’s systems through the implementation of SAP. ',
            'Ended the period with cash and cash equivalents of $908.9 million as well as no debt other than a low-interest, unsecured term loan associated with the French government’s response to COVID-19. '
        ],
        quarterOverviewPoints: [],
    },
    {
        quarter: 'Q3',
        year: 2022,
        summaryPoints: [
            'Net sales were $1.186 billion, compared to $1.297 billion in the prior year’s third quarter. ',
            'Sales attributable to new and expanded brand relationships were strong in the quarter, while sales in the collectibles category remained strong on a year-to-date basis. ',
            'Selling, general and administrative expenses (“SG&A”) were $387.9 million, or 32.7% of sales, compared to $421.5 million, or 32.5% of sales, in the prior year’s third quarter. Notably, SG&A as a percentage of revenue was down on a sequential basis from 34.1% in Q2 of this year, reflecting the Company’s ongoing cost reduction efforts. ',
            'Inventory was $1.131 billion at the close of the period, compared to $1.141 billion at the close of the prior year’s third quarter. ',
            'Cash, cash equivalents and marketable securities were $1.042 billion at the close of the third quarter. ',
            'Long-term debt remains limited to a low-interest, unsecured term loan associated with the French government’s response to COVID-19. ',
        ],
        quarterOverviewPoints: [],
    },
    {
        quarter: 'Q4',
        year: 2022,
        summaryPoints: [],
        quarterOverviewPoints: [
            'Net sales were $2.226 billion, compared to $2.254 billion in the prior year’s fourth quarter. ',
            'Selling, general and administrative (“SG&A”) expenses were $453.4 million, or 20.4% of sales, compared to $538.9 million, or 23.9% of sales, in the prior year’s fourth quarter. ',
            'Net income was $48.2 million, compared to a net loss of $147.5 million for the prior year’s fourth quarter. ',
            'Inventory was $682.9 million at the close of the period, compared to $915.0 million at the close of the prior year’s fourth quarter, reflecting the Company’s ongoing focus on maintaining a healthy inventory position. ',
            'Cash, cash equivalents and marketable securities were $1.391 billion at the close of the quarter. ',
            'Long-term debt remains limited to a low-interest, unsecured term loan associated with the French government’s response to COVID-19. ',
        ],
        yearOverviewPoints:[
            'Generated net sales of $5.927 billion for the fiscal year, compared to $6.011 billion for fiscal year 2021. ',
            'Increased full-year sales in the collectibles category, which is an area in which the Company continues prioritizing long-term growth. ',
            'Completed the majority of implementations and upgrades related to the Company’s infrastructure, systems, shipping capabilities, and online and mobile platforms. ',
            'Initiated cost cutting initiatives and headcount reductions over the course of the year to increase operational efficiency. ',
            'Established an equity incentive program for store leaders and tenured associates to increase their compensation and strengthen alignment of interests with fellow stockholders. ',
            'Set a go-forward strategic direction focused on efficiency, profitability and pragmatic growth.',
        ],
    },
    {
        quarter: 'Q1',
        year: 2023,
        summaryPoints: [
            'Net sales were $1.237 billion for the period, compared to $1.378 billion in the prior year’s first quarter. ',
            'Selling, general and administrative (“SG&A") expenses were $345.7 million, or 27.9% of net sales for the period, compared to $452.2 million, or 32.8% of net sales, in the prior year’s first quarter. ',
            'Net loss was $50.5 million for the period, compared to a net loss of $157.9 million for the prior year’s first quarter. ',
            'Transition costs related to European restructuring efforts were $14.5 million for the period. For the second quarter, the Company will continue to incur transition charges. ',
            'Cash, cash equivalents and marketable securities were $1.310 billion at the close of the quarter. ',
            'Long-term debt remains limited to one low-interest, unsecured term loan associated with the French government’s response to COVID-19. ',
        ],
        quarterOverviewPoints: [],
    },
    {
        quarter: 'Q2',
        year: 2023,
        summaryPoints: [
            'Net sales were $1.164 billion for the period, compared to $1.136 billion in the prior year’s second quarter.',
            'Selling, general and administrative (“SG&A") expenses were $322.5 million, or 27.7% of net sales for the period, compared to $387.5 million, or 34.1% of net sales, in the prior year’s second quarter.',
            'Net loss was $2.8 million for the period, compared to a net loss of $108.7 million for the prior year’s second quarter.',
            'Transition costs related to European restructuring efforts were $4.3 million for the second quarter.',
            'Cash, cash equivalents and marketable securities were $1.195 billion at the close of the quarter.',
            'Long-term debt remains limited to one low-interest, unsecured term loan associated with the French government’s response to COVID-19.',
        ],
        quarterOverviewPoints: [],
    },


];
