import { ChapterInterface } from "./chapter.class";


export const chapterConfigs: ChapterInterface[] = [
    {
        title: 'GameStop: a dying brick and mortar retailer',
        yearGroup: '2020',
        dateStartYYYYMMDD: '2020-01-01',
        dateEndYYYYMMDD: '2020-12-31',
        subtitle: 'The legacy company GameStop as it was before 2021',
        description:
            [
                'The GameStop company as most people knew it and continue to perceive it, that retail store in the mall where you could go to trade in your old games for a pittance.',
                'Who would ever believe that a company such as this would ever have any major significance?'
            ],
        subchapters: [],
    },
    {
        title: 'The sneeze of 2021',
        yearGroup: '2021',
        subtitle: 'An unprecendent social media phenomenon has revealed opportunities and vulnerabilities.  GameStop is now run by an entirely new board of directors, and obtains a pile of cash by selling high-priced shares to the market.  GME shareholders discover DRS.',
        dateStartYYYYMMDD: '2021-01-01',
        dateEndYYYYMMDD: '2021-12-31',
        description: [],
        subchapters: [],
    },
    {
        title: 'Billions of dollars directly registered by shareholders',
        yearGroup: '2022',
        subtitle: 'GameStop investors educate themselves and directly register billions of dollars worth of GME',
        dateStartYYYYMMDD: '2022-01-01',
        dateEndYYYYMMDD: '2022-12-31',
        description: [],
        subchapters: [],
    },
    {
        title: 'Can the company become profitable?',
        yearGroup: '2023',
        subtitle: '25% of the company is owned by directly registered shareholders, but investment momentum has dissipated.  Competing narratives vy for the truth.',
        dateStartYYYYMMDD: '2023-01-01',
        dateEndYYYYMMDD: '2023-12-31',
        description: [],
        subchapters: [],
    },
    {
        title: 'Outcomes of pressure and time',
        yearGroup: '2024',
        subtitle: 'GameStop was profitable in FY2023.  Roaring Kitty has returned.  The winds are changing.',
        dateStartYYYYMMDD: '2024-01-01',
        dateEndYYYYMMDD: '2024-12-31',
        description: [],
        subchapters: [],
    },
    // {
    //     title: 'the sneeze, and immediate aftermath',
    //     subtitle: 'January 2021 to March 2021',
    //     dateStartYYYYMMDD: '2021-01-01',
    //     dateEndYYYYMMDD: '2021-03-23',
    //     description: [],
    //     subchapters: [],
    // },
    // {
    //     title: 'new leadership, new opportunities',
    //     subtitle: 'April 2021 to September 2021',
    //     dateStartYYYYMMDD: '2021-03-024',
    //     dateEndYYYYMMDD: '2021-09-09',
    //     description: [],
    //     subchapters: [],
    // },
    // {
    //     title: 'DRS discovered',
    //     subtitle: 'September 2021 to March 2022',
    //     dateStartYYYYMMDD: '2021-09-10',
    //     dateEndYYYYMMDD: '2022-03-18',
    //     description: [],
    //     subchapters: [],
    // },
    // {
    //     title: 'DRS to 25%',
    //     subtitle: 'March 2022 to December 2022',
    //     dateStartYYYYMMDD: '2022-03-19',
    //     dateEndYYYYMMDD: '2022-12-07',
    //     description: [],
    //     subchapters: [],
    // },
    // {
    //     title: 'loss of momentum, community divisions, an apparent stalemate',
    //     subtitle: 'December 2022 to September 2023',
    //     dateStartYYYYMMDD: '2022-12-08',
    //     dateEndYYYYMMDD: '2023-09-06',
    //     description: [],
    //     subchapters: [],
    // },
    // {
    //     title: 'competing narratives; (psychological warfare); pre-moass',
    //     subtitle: 'September 2023 to present',
    //     dateStartYYYYMMDD: '2023-09-07',
    //     dateEndYYYYMMDD: '',
    //     description: [],
    //     subchapters: [],
    // },
];